/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DownloadList: typeof import('./components/DownloadList.vue')['default']
    DropdownSelect: typeof import('./components/DropdownSelect.vue')['default']
    FileBrowser: typeof import('./components/FileBrowser.vue')['default']
    FileInfoPanel: typeof import('./components/FileInfoPanel.vue')['default']
    HelpModal: typeof import('./components/HelpModal.vue')['default']
    LucideAlertCircle: typeof import('@lucide/vue')['AlertCircle']
    LucideArchive: typeof import('@lucide/vue')['Archive']
    LucideArrowLeftRight: typeof import('@lucide/vue')['ArrowLeftRight']
    LucideArrowRight: typeof import('@lucide/vue')['ArrowRight']
    LucideBoxes: typeof import('@lucide/vue')['Boxes']
    LucideCheck: typeof import('@lucide/vue')['Check']
    LucideCheckCircle2: typeof import('@lucide/vue')['CheckCircle2']
    LucideChevronDown: typeof import('@lucide/vue')['ChevronDown']
    LucideChevronRight: typeof import('@lucide/vue')['ChevronRight']
    LucideCircleHelp: typeof import('@lucide/vue')['CircleHelp']
    LucideCircleSlash: typeof import('@lucide/vue')['CircleSlash']
    LucideCircleX: typeof import('@lucide/vue')['CircleX']
    LucideClock: typeof import('@lucide/vue')['Clock']
    LucideCopy: typeof import('@lucide/vue')['Copy']
    LucideDownload: typeof import('@lucide/vue')['Download']
    LucideExternalLink: typeof import('@lucide/vue')['ExternalLink']
    LucideFile: typeof import('@lucide/vue')['File']
    LucideFileJson: typeof import('@lucide/vue')['FileJson']
    LucideFilePlay: typeof import('@lucide/vue')['FilePlay']
    LucideFiles: typeof import('@lucide/vue')['Files']
    LucideFileVideo: typeof import('@lucide/vue')['FileVideo']
    LucideFolder: typeof import('@lucide/vue')['Folder']
    LucideHardDrive: typeof import('@lucide/vue')['HardDrive']
    LucideHash: typeof import('@lucide/vue')['Hash']
    LucideInbox: typeof import('@lucide/vue')['Inbox']
    LucideLayers: typeof import('@lucide/vue')['Layers']
    LucideLink: typeof import('@lucide/vue')['Link']
    LucideLoader2: typeof import('@lucide/vue')['Loader2']
    LucideLoaderCircle: typeof import('@lucide/vue')['LoaderCircle']
    LucideMoon: typeof import('@lucide/vue')['Moon']
    LucideMousePointer2: typeof import('@lucide/vue')['MousePointer2']
    LucideMusic: typeof import('@lucide/vue')['Music']
    LucidePackage: typeof import('@lucide/vue')['Package']
    LucidePackageOpen: typeof import('@lucide/vue')['PackageOpen']
    LucidePackageX: typeof import('@lucide/vue')['PackageX']
    LucidePlay: typeof import('@lucide/vue')['Play']
    LucidePlus: typeof import('@lucide/vue')['Plus']
    LucideRefreshCw: typeof import('@lucide/vue')['RefreshCw']
    LucideSearch: typeof import('@lucide/vue')['Search']
    LucideSettings: typeof import('@lucide/vue')['Settings']
    LucideSun: typeof import('@lucide/vue')['Sun']
    LucideTag: typeof import('@lucide/vue')['Tag']
    LucideTrash2: typeof import('@lucide/vue')['Trash2']
    LucideTriangleAlert: typeof import('@lucide/vue')['TriangleAlert']
    LucideUser: typeof import('@lucide/vue')['User']
    LucideX: typeof import('@lucide/vue')['X']
    LucideXCircle: typeof import('@lucide/vue')['XCircle']
    NavBar: typeof import('./components/layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideGameList: typeof import('./components/layout/SideGameList.vue')['default']
    SidePageList: typeof import('./components/layout/SidePageList.vue')['default']
    TagBadge: typeof import('./components/TagBadge.vue')['default']
    UsmPlayerModal: typeof import('./components/UsmPlayerModal.vue')['default']
    UsmSourcePickerModal: typeof import('./components/UsmSourcePickerModal.vue')['default']
  }
}
